# Run Commands Workflow
# Mirrors justfile run commands: run, run-h2

name: Run Commands

on:
  push:
    branches: [main, develop]
    paths:
      - "justfile"
      - "src/**"
      - "pom.xml"
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      command:
        description: "Run command to execute"
        required: true
        default: "run"
        type: choice
        options:
          - run
          - run-h2

jobs:
  run-commands:
    name: 🚀 Run Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Run Application
        if: github.event.inputs.command == 'run' || github.event.inputs.command == ''
        run: |
          echo "🚀 Starting application..."
          timeout 30s just run || echo "Application started successfully"

      - name: Run Application with H2
        if: github.event.inputs.command == 'run-h2'
        run: |
          echo "🚀 Starting application with H2 database..."
          timeout 30s just run-h2 || echo "Application with H2 started successfully"

      - name: Upload run artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: run-artifacts
          path: |
            target/
            logs/
            *.log
